# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/ui_files\GameEditorCentralWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameEditorCentralWidget(object):
    def setupUi(self, GameEditorCentralWidget):
        GameEditorCentralWidget.setObjectName("GameEditorCentralWidget")
        GameEditorCentralWidget.resize(400, 300)

        self.retranslateUi(GameEditorCentralWidget)
        QtCore.QMetaObject.connectSlotsByName(GameEditorCentralWidget)

    def retranslateUi(self, GameEditorCentralWidget):
        _translate = QtCore.QCoreApplication.translate
        GameEditorCentralWidget.setWindowTitle(_translate("GameEditorCentralWidget", "Form"))
