# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/ui_files\LogDockWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogWidget(object):
    def setupUi(self, LogWidget):
        LogWidget.setObjectName("LogWidget")
        LogWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(LogWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(LogWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.clearLogButton = QtWidgets.QPushButton(self.frame)
        self.clearLogButton.setObjectName("clearLogButton")
        self.horizontalLayout.addWidget(self.clearLogButton, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame)
        self.logTreeWidget = QtWidgets.QTreeWidget(LogWidget)
        self.logTreeWidget.setObjectName("logTreeWidget")
        self.verticalLayout.addWidget(self.logTreeWidget)

        self.retranslateUi(LogWidget)
        QtCore.QMetaObject.connectSlotsByName(LogWidget)

    def retranslateUi(self, LogWidget):
        _translate = QtCore.QCoreApplication.translate
        LogWidget.setWindowTitle(_translate("LogWidget", "Form"))
        self.clearLogButton.setText(_translate("LogWidget", "Clear"))
        self.logTreeWidget.headerItem().setText(0, _translate("LogWidget", "Level"))
        self.logTreeWidget.headerItem().setText(1, _translate("LogWidget", "File"))
        self.logTreeWidget.headerItem().setText(2, _translate("LogWidget", "Line"))
        self.logTreeWidget.headerItem().setText(3, _translate("LogWidget", "Time"))
        self.logTreeWidget.headerItem().setText(4, _translate("LogWidget", "Message"))
