# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/ui_files\LogDockWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogWidget(object):
    def setupUi(self, LogWidget):
        LogWidget.setObjectName("LogWidget")
        LogWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(LogWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(LogWidget)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout.addWidget(self.treeWidget)

        self.retranslateUi(LogWidget)
        QtCore.QMetaObject.connectSlotsByName(LogWidget)

    def retranslateUi(self, LogWidget):
        _translate = QtCore.QCoreApplication.translate
        LogWidget.setWindowTitle(_translate("LogWidget", "Form"))
        self.treeWidget.headerItem().setText(0, _translate("LogWidget", "Level"))
        self.treeWidget.headerItem().setText(1, _translate("LogWidget", "File"))
        self.treeWidget.headerItem().setText(2, _translate("LogWidget", "Line"))
        self.treeWidget.headerItem().setText(3, _translate("LogWidget", "Time"))
        self.treeWidget.headerItem().setText(4, _translate("LogWidget", "Message"))
